version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
    - nolintlint
    # Error handling
    - errorlint      # proper error wrapping with errors.Is/As
    - nilerr         # return nil when err != nil
    # Safety
    - bodyclose      # HTTP response body must be closed
    - forcetypeassert # type assertions must be checked
    # Code quality
    - predeclared    # shadowing of predeclared identifiers
    - dupword        # duplicate words in comments
    # Modern Go idioms (Go 1.21+)
    - modernize      # use modern Go idioms (any, slices.Contains, etc.)
    - perfsprint     # faster alternatives to fmt.Sprintf/Errorf
    - exhaustive     # check exhaustiveness of enum switch statements
    - intrange       # use Go 1.22 range-over-integers
    - copyloopvar    # detect issues with loop variable copying
    # Consistency
    - recvcheck      # check receiver type consistency
    - nilnil         # check for nil,nil returns (excluding intentional cases)
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vertti/preflight

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
