run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - nolintlint

linters-settings:
  goimports:
    local-prefixes: github.com/vertti/preflight
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
