version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic
    - nolintlint
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    nolintlint:
      require-explanation: true
      require-specific: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/vertti/preflight

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
