coverage:
  status:
    project:
      default:
        target: 75%
    patch:
      default:
        target: 70%

comment:
  layout: "header, diff, files"
  hide_project_coverage: false

ignore:
  - "cmd/preflight/cmd_*.go"  # Cobra wiring, init() functions
